### ISSUE TITLE
Problems with enemy respawns in Survival mode

### ISSUE THREAD

**Issue by Replicant1982** [ImanCol/Vig2Online#3]
Sometimes only the first enemy spawns.
Sometimes the stop spawning after the 10th kill.
Sometimes they stop spawning after the 12th kill.
![image (11)](https://github.com/ImanCol/Vig2Online/assets/135526724/fd0408a7-395b-4469-b689-60479422464c)

**Comment by Replicant1982** [comment]
Update: issue only present in Route66 (first map).

**Comment by ImanCol** [comment]
Possibly caused by Dakota, I can consider this resolved. If the problem reappears, you can open it again
