### ISSUE TITLE
Problems with weapon and pickups respawn in Survival Mode

### ISSUE THREAD

**Issue by Replicant1982** [ImanCol/Vig2Online#4]
during the last row of enemies in Survival Mode, the weapons and pickups (Shield, Double Damage and Radar Jammer) stopped to spawn.
![image (11)](https://github.com/ImanCol/Vig2Online/assets/135526724/724bacdb-a6eb-46cf-bc66-741ce6d40497)

**Comment by Replicant1982** [comment]
Update: issue only present in Route66 (first map).

**Comment by ImanCol** [comment]
Can you confirm that it was resolved?
